### ISSUE TITLE
Overhaul main README

### ISSUE THREAD

**Issue by johnbaldwin** [appsembler/figures#437]
The current README is horribly out of date and it is also serving as the changelog file, eating valuable reading real estate.

# Tasks to overhaul README

- [ ]  Update CHANGELOG and remove changelog content from README.md
- [ ] Structure the doc (see doc structure below)
- [ ] Include content: https://github.com/appsembler/figures/issues/436

## WIP Doc structure
- **Overview**: This section is the 30 second read. What's Figures? Is it active? Is it useful to me? Do I continue reading?

- **What is Figures?** After the 30 second read, provide some more details, still brief. We ought to have architecture doc(s) and link from here
- Getting started with Figures
- Figures devsite
- Installing Figures in Open edX

- Contributing
- Reporting bugs
- reporting security issues
